version: '3'

services:

  djangoapp:
    build: .
    volumes:
      - .:/opt/services/django_app/src
      - static_volume:/opt/services/django_app/src/www/static
      - media_volume:/opt/services/django_app/src/www/media
    networks:
      - nginx_network
      - database_network
    depends_on:
      - database

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/django_app/src/www/static
      - media_volume:/opt/services/django_app/src/www/media
    depends_on:
      - djangoapp
      - redis
    networks:
      - nginx_network

  redis:
    image: "redis:alpine"

  database:
    image: postgres:10
    env_file:
      - config/db/database_env
    networks:
      - database_network
    volumes:
      - database_volume:/var/lib/postgresql/data


  celery:
    build: .
    command: celery -A restaurant_menu worker -l INFO
    volumes:
      - .:/opt/services/django_app/src
    depends_on:
      - database
      - redis

  celery-beat:
    build: .
    command: celery -A restaurant_menu beat -l INFO
    volumes:
      - .:/opt/services/django_app/src
    depends_on:
      - database
      - redis

  flower:
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=5555
      - FLOWER_BASIC_AUTH=flower:flower
    ports:
      - 5555:5555
    depends_on:
      - database
      - redis

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  database_volume:
  static_volume:
  media_volume:
