# Generated by Django 3.1.2 on 2020-10-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_pastbinlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastbinlink',
            options={'verbose_name': 'Ссылка на меню', 'verbose_name_plural': 'Ссылка на меню'},
        ),
    ]
